trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

steps:
- template: templates/steps/deploy-steps-template.yml
  parameters:
    location: 'eastus'
    repoURL: 'https://github.com/Azure-Samples/eventgrid-viewer-blazor.git'