parameters:
  - name: 'location'
    type: string
  - name: 'repoURL'
    type: string

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: {your_service_connection}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      chmod +x infrastructure/azuredeploy.sh &&
      bash infrastructure/azuredeploy.sh -g $(resourceGroup) -s $(siteName) -p $(hostingPlanName) \
      -l ${{ parameters.location }} -r ${{ parameters.repoURL }}  -b $(branch)