###########################################################################################################################
# Descripton: GitHub Action Workflow used to build the eventgrid-viewer-blazor application.
###########################################################################################################################
on:
    push:
      branches:
        - main
      paths:
      - 'src/**'
      - '.github/workflows/build.yml'        
    pull_request:
      branches:
        - main
      paths:
      - 'src/**'
      - '.github/workflows/build.yml'

name: 'Build'

env:
  NET_CORE_VERSION: '5.0.x'
  CONFIGURATION: 'Release'

jobs:
  dev-build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@master

    - name: 'Use .Net Core ${{ env.NET_CORE_VERSION }}'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NET_CORE_VERSION }}

    - name: 'Build with dotnet'
      run: dotnet build src/Blazor.EventGridViewer.ServerApp/Blazor.EventGridViewer.ServerApp.csproj -c ${{ env.CONFIGURATION }}

    - name: 'Run Unit Tests'
      run: dotnet test src/Blazor.EventGridViewer.Unit.Tests/Blazor.EventGridViewer.Unit.Tests.csproj