name: build

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Dotnet-build:
    uses: Strongmind/public-reusable-workflows/.github/workflows/dotnet-build.yml@main
    with: 
      test: true
      project_path: src/Blazor.EventGridViewer.ServerApp/Blazor.EventGridViewer.ServerApp.csproj
      project_path_test: src/Blazor.EventGridViewer.Unit.Tests/Blazor.EventGridViewer.Unit.Tests.csproj
      dotnet-version: 3.1.x
    secrets: inherit
